'use strict';
const PROTOCOL_VERSION = 2;
const MIN_COMPATIBLE_PROTOCOL_VERSION = 2;
const PORT = 34567;
const UDP_PORT = 34568;
const SERVICE_NAME = 'adestio-node';
module.exports = { PROTOCOL_VERSION, MIN_COMPATIBLE_PROTOCOL_VERSION, PORT, UDP_PORT, SERVICE_NAME };
